// This file is auto-generated by @hey-api/openapi-ts

export { getInfoVersion, type Options } from './sdk.gen';
export type { ClientOptions, GetInfoVersionData, GetInfoVersionResponse, GetInfoVersionResponses } from './types.gen';
