// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetInfoVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Info/version';
};

export type GetInfoVersionResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetInfoVersionResponse = GetInfoVersionResponses[keyof GetInfoVersionResponses];
