// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiEmailRegistrationRegistrationEmailByTokenData, GetApiEmailRegistrationRegistrationEmailByTokenResponses, GetInfoVersionData, GetInfoVersionResponses, GetSessionData, GetSessionResponses, GetSessionsData, GetSessionsResponses, PostApiEmailRegistrationLoginData, PostApiEmailRegistrationLoginResponses, PostApiEmailRegistrationRegistrationConfirmRegistrationByTokenData, PostApiEmailRegistrationRegistrationConfirmRegistrationByTokenResponses, PostApiEmailRegistrationRegistrationInitiateRegistrationData, PostApiEmailRegistrationRegistrationInitiateRegistrationResponses, PostLogoutData, PostLogoutResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiEmailRegistrationRegistrationInitiateRegistration = <ThrowOnError extends boolean = false>(options?: Options<PostApiEmailRegistrationRegistrationInitiateRegistrationData, ThrowOnError>) => (options?.client ?? client).post<PostApiEmailRegistrationRegistrationInitiateRegistrationResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/EmailRegistration/registration/initiateRegistration',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postApiEmailRegistrationRegistrationConfirmRegistrationByToken = <ThrowOnError extends boolean = false>(options: Options<PostApiEmailRegistrationRegistrationConfirmRegistrationByTokenData, ThrowOnError>) => (options.client ?? client).post<PostApiEmailRegistrationRegistrationConfirmRegistrationByTokenResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/EmailRegistration/registration/confirmRegistration/{token}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiEmailRegistrationRegistrationEmailByToken = <ThrowOnError extends boolean = false>(options: Options<GetApiEmailRegistrationRegistrationEmailByTokenData, ThrowOnError>) => (options.client ?? client).get<GetApiEmailRegistrationRegistrationEmailByTokenResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/EmailRegistration/registration/email/{token}',
    ...options
});

export const postApiEmailRegistrationLogin = <ThrowOnError extends boolean = false>(options?: Options<PostApiEmailRegistrationLoginData, ThrowOnError>) => (options?.client ?? client).post<PostApiEmailRegistrationLoginResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/EmailRegistration/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getInfoVersion = <ThrowOnError extends boolean = false>(options?: Options<GetInfoVersionData, ThrowOnError>) => (options?.client ?? client).get<GetInfoVersionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/Info/version',
    ...options
});

export const postLogout = <ThrowOnError extends boolean = false>(options?: Options<PostLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostLogoutResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/logout',
    ...options
});

export const getSession = <ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>) => (options?.client ?? client).get<GetSessionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/session',
    ...options
});

export const getSessions = <ThrowOnError extends boolean = false>(options?: Options<GetSessionsData, ThrowOnError>) => (options?.client ?? client).get<GetSessionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/sessions',
    ...options
});
