// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AuthRequest = {
    email?: string | null;
    password?: string | null;
};

export type ConfirmRegistrationRequest = {
    code?: string | null;
};

export type RegistrationEmailResponse = {
    email?: string | null;
};

export type RegistrationResponse = {
    registrationToken?: string | null;
};

export type Session = {
    sessionId?: string | null;
    userId?: number;
    readonly createdAt?: string;
};

export type SessionWritable = {
    sessionId?: string | null;
    userId?: number;
};

export type PostApiEmailRegistrationRegistrationInitiateRegistrationData = {
    body?: AuthRequest;
    path?: never;
    query?: never;
    url: '/api/EmailRegistration/registration/initiateRegistration';
};

export type PostApiEmailRegistrationRegistrationInitiateRegistrationResponses = {
    /**
     * OK
     */
    200: RegistrationResponse;
};

export type PostApiEmailRegistrationRegistrationInitiateRegistrationResponse = PostApiEmailRegistrationRegistrationInitiateRegistrationResponses[keyof PostApiEmailRegistrationRegistrationInitiateRegistrationResponses];

export type PostApiEmailRegistrationRegistrationConfirmRegistrationByTokenData = {
    body?: ConfirmRegistrationRequest;
    path: {
        token: string;
    };
    query?: never;
    url: '/api/EmailRegistration/registration/confirmRegistration/{token}';
};

export type PostApiEmailRegistrationRegistrationConfirmRegistrationByTokenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiEmailRegistrationRegistrationEmailByTokenData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/api/EmailRegistration/registration/email/{token}';
};

export type GetApiEmailRegistrationRegistrationEmailByTokenResponses = {
    /**
     * OK
     */
    200: RegistrationEmailResponse;
};

export type GetApiEmailRegistrationRegistrationEmailByTokenResponse = GetApiEmailRegistrationRegistrationEmailByTokenResponses[keyof GetApiEmailRegistrationRegistrationEmailByTokenResponses];

export type PostApiEmailRegistrationLoginData = {
    body?: AuthRequest;
    path?: never;
    query?: never;
    url: '/api/EmailRegistration/login';
};

export type PostApiEmailRegistrationLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetInfoVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Info/version';
};

export type GetInfoVersionResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetInfoVersionResponse = GetInfoVersionResponses[keyof GetInfoVersionResponses];

export type PostLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type PostLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type GetSessionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetSessionsData = {
    body?: never;
    path?: never;
    query?: {
        userId?: number;
    };
    url: '/sessions';
};

export type GetSessionsResponses = {
    /**
     * OK
     */
    200: Array<Session>;
};

export type GetSessionsResponse = GetSessionsResponses[keyof GetSessionsResponses];
